# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-01 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_auto_20180101_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='time_Of_Arrival',
            field=models.DateTimeField(default='2000-09-04 06:00'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='time_Of_Departure',
            field=models.DateTimeField(default='2000-09-04 06:00'),
        ),
    ]
