# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_auto_20180108_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change',
            old_name='cityA',
            new_name='city_Of_Arrival',
        ),
        migrations.RenameField(
            model_name='change',
            old_name='cityB',
            new_name='city_Of_Departure',
        ),
        migrations.RenameField(
            model_name='change',
            old_name='duration',
            new_name='duration_Of_Trip',
        ),
        migrations.RenameField(
            model_name='change',
            old_name='Arrival',
            new_name='time_Of_Arrival',
        ),
        migrations.RenameField(
            model_name='change',
            old_name='Departure',
            new_name='time_Of_Departure',
        ),
        migrations.AddField(
            model_name='change',
            name='route',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='trip.Trips'),
        ),
    ]
